-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "priority" DROP NOT NULL,
ALTER COLUMN "priority" SET DEFAULT 'None',
ALTER COLUMN "deadline" DROP NOT NULL,
ALTER COLUMN "deadline" SET DEFAULT CURRENT_TIMESTAMP;
